alias gs="git status"
alias ga="git add"
alias gca="git commit --amend"
alias gfa="git fetch --all"
alias gpf="git push -f"
alias gp="git pull"
alias gph="git push"
alias gc="git checkout"
alias gr="git rebase"
alias gb="git branch"
alias cb="git rev-parse --abbrev-ref HEAD"
alias cbn="cb | pbcopy"
alias gpu="git push -u origin"
alias glog="git log --all --graph --decorate --name-only"

alias reload-shell-kit="source ~/.zprofile"
